application:
  appName: sgcservice

  mail:
    endereco-remetente: luanalencar134@gmail.com
    nome-remetente: funcionario

spring:
  application:
    name: sgcserviceX

    cloud:
      stream:
        bindings:
          mailer:
            destination: mailer

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/sgc
    username: sgc
    password: sgc

    hikari:
      poolName: Hikari
      auto-commit: false

  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  #        drop-first: true

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: basistreinamento@gmail.com
    password: basis123123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          quitwait: false

  spring:
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration,org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
    application:
      name: sgcservice
    cloud:
      stream:
        kafka:
          binder:
            brokers: localhost
            zk-nodes: localhost
        bindings:
          mailer:
            destination: mailer
    jmx:
      enabled: false
    data:
      jest:
        # Aumentar o timeout quando executar o sistema pela primeira vez para evitar problema
        # na criação dos indexs no elasticsearch
        read-timeout: 10000
      jpa:
        repositories:
          bootstrap-mode: deferred
    jpa:
      open-in-view: false
      properties:
        hibernate.jdbc.time_zone: UTC
        hibernate.id.new_generator_mappings: true
        hibernate.connection.provider_disables_autocommit: true
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
        # modify batch size as necessary
        hibernate.jdbc.batch_size: 25
        hibernate.order_inserts: true
        hibernate.order_updates: true
        # modify fetch size as necessary
        hibernate.jdbc.fetch_size: 150
        hibernate.criteria.literal_handling_mode: BIND
        hibernate.query.fail_on_pagination_over_collection_fetch: true
        hibernate.query.in_clause_parameter_padding: true
        hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
        hibernate.cache.use_minimal_puts: true
        hibernate.cache.hazelcast.instance_name: sgcservice
        hibernate.cache.hazelcast.use_lite_member: true
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

jhipster:
  cache: # Cache configuration
    hazelcast: # Hazelcast distributed cache
      time-to-live-seconds: 3600
      backup-count: 1
      management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
        enabled: false
        update-interval: 3
        url: http://localhost:8180/hazelcast-mancenter

server:
  port: 8080